added working display/sd-card project wich uses only one pll

diff --git a/software/create-app-makefile b/software/create-app-makefile
--- a/software/create-app-makefile
+++ b/software/create-app-makefile
@@ -1,6 +1,8 @@
 #!/bin/bash
+#
 
-# the environment variables  PROJECT_NAME, QUARTUS_PROJECT_DIR and BSP_DIR  are set by the makefile which calls this script
+# the environment variables  PROJECT_NAME, BSP_DIR and SOPC_FILE are set by the makefile which calls this script
+
 
 SRC_DIR=./src
 
@@ -37,5 +39,17 @@ $cmd || {
     echo "nios2-app-generate-makefile failed"
     exit 1
 }
+
+if [ -z "$SKIP_MAKE" ]; then
+        cmd="make -C ${PROJECT_NAME}"
+
+        echo "create-this-app: Running \"$cmd\""
+        $cmd || {
+        echo "make failed"
+            exit 1
+        }
+
+fi
+
 
 exit 0
